name: Build Preview

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      
      - name: install rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Rust Cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: src-tauri -> target

      - name: install dependencies
        run: npm ci
      
      - name: build app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v__VERSION__ # This is just a placeholder for the preview build
          releaseName: "Preview v__VERSION__"
          releaseDraft: true
          prerelease: true

      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ProClubs-Stats-Windows
          path: |
            src-tauri/target/release/bundle/msi/*.msi
